### PR TITLE
Neural operators part 1

### PR DESCRIPTION
**Pull request by schneidermc**
@minnerbe and I added a blog post about our presentation on neural operators. We tried to capture everything that was said in the presentation and leave out some technical details, favoring readability and conciseness over mathematical details.

What do you think about this, @kristinbranson? Can you please give it a quick read before we merge and publish it? Thanks!

### CODE REVIEW

**Comment by kristinbranson** [comment]
Looks good to me! I pulled the change in. 

Minor comments -- take them or leave them, up to you!

In the first sentence -- "Neural Operators are a generalization of neural networks to continuous domains, i.e., they learn to map functions to other functions" -- I found it confusing what continuous meant, since the input/output of a neural net is continuous, that is, each node is continuous. The explanation later on made more sense, "Neural Operators can be seen as a generalization of convolutional neural networks (CNNs) to continuous domains. While CNNs feature convolutions with small kernels on regular discrete grids, neural operators have a continuous kernel that is convolved with the whole function in each layer." 
I don't have enough of a background in PDEs to understand the PDE explanation, not sure I'm representative, though. Maybe an example of a, u and f would help for people coming from a CS/stats background? Maybe walking through one of the practical examples in each section as things are defined could be helpful, rather than having all the examples at the end? E.g. for the Poisson equation, you could also have what the actual inputs and outputs of the network are, which would make the sample input./output notion clearer? 
Do you have any opinions you feel comfortable including in the blog post about what you think about the approach? What you take away, what you liked, when you might use these approaches, how knowing this would affect your work?

**Comment by kristinbranson** [comment]
PS Are all the figures your own? If any are not, maybe put a link to the source in their captions?

**Comment by kristinbranson** [comment]
PPS I hear you can include notebooks in quarto, not sure if that is of interest to you
https://quarto.org/docs/authoring/notebook-embed.html

**Comment by minnerbe** [comment]
Thanks for the feedback, @kristinbranson! We implemented almost all your suggestions (except for the notebook integration, since we weren't comfortable just embedding a notebook from someone else - that looks like it could be super useful for future posts, though). You can find the diff [here](https://github.com/janelia-cvml/blog/compare/main...neural-operators-pt1).

You are right, the use of "continuous" was a bit ambiguous and the introduction was a bit abstract. I hope that the updated usage of the word and the added example help to explain the overall concept better. We also added a small takeaway section.

If this looks good to you, feel free to merge and publish the post!

**Pull request merged**
